### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by petterik** [petterik/xfseq#1]
- [ ] Complete primitive reduce invokations.
- [ ] Complete all transducers
- [ ] consume-kv + extending all transducers to support another arity.
- [x] consume needs to call (rf val) after the reduce
- [ ] CLI for testing memory usage.

**Comment by petterik** [comment]
- [x] ILongSeqable should create chunks, not a single chunk.

- [ ] Create a primitive reduce protocol.
- [ ] Implement it for IChunkedSeq

Create a function that walks a function body and replaces some of its elements with transformations:
* primitive .invoke
* Type hints
* ?

Can one make ☝️ general enough to support type hinting argument vectors for fns with multiple declarations? Or should that me a different function?
